version: '3.8'

services:
  ai-tech-lead:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PORT=5001
    env_file:
      - .venv/gitignore/.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for future caching/queue functionality
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data: